name: CI

on: push

jobs:
  parallel-runs:
    name: Parallel 4x
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        machines: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: run tests
        uses: cypress-io/github-action@v1
        timeout-minutes: 5
        with:
          record: false
          parallel: true
          group: GH Action parallel
          start: npm start
          wait-on: "http://localhost:8080"
          config: baseUrl=http://localhost:8080
